### ISSUE TITLE
缺少gerber_exporter.png

### ISSUE THREAD

**Issue by sudemo** [hsiang-lee/gerber-parser#16]
cmake生成成功
vs2017编译报错

1>------ 已启动生成: 项目: gerber2image, 配置: Debug x64 ------
1>Automatic RCC for gerber2image.qrc
1>
1>AutoRcc subprocess error
1>------------------------
1>The rcc process failed to compile
1>  "SRC:/example/gerber2image/gerber2image.qrc"
1>into
1>  "SRC:/build/example/gerber2image/gerber2image_autogen/include_Debug/EWIEGA46WW/qrc_gerber2image_CMAKE_.cpp"
1>
1>Command
1>-------
1>C:/Qt5.12.9/5.12.9/msvc2017_64/bin/rcc.exe -name gerber2image -o D:/CODING/CPP/GerberParse/gerber-parser-master/build/example/gerber2image/gerber2image_autogen/include_Debug/EWIEGA46WW/qrc_gerber2image_CMAKE_.cpp D:/CODING/CPP/GerberParse/gerber-parser-master/example/gerber2image/gerber2image.qrc
1>
1>Output
1>------
1>RCC: Error in 'D:/GerberParse/gerber-parser-master/example/gerber2image/gerber2image.qrc': Cannot find file 'gerber_exporter.png'
1>

**Comment by hsiang-lee** [comment]
好的，感谢你的反馈~

**Comment by hsiang-lee** [comment]
已经解决了，请拉最新的代码。

**Comment by sudemo** [comment]
> 已经解决了，请拉最新的代码。

非常感谢！
