### ISSUE TITLE
make_unique(): "Microsoft C++ exception: std::bad_alloc at memory location"

### ISSUE THREAD

**Issue by tieutuanbao** [hsiang-lee/gerber-parser#34]
This error occurs when i debug app, that compile with MSVC 2017 X64 on Visual studio.

`auto parser = std::make_unique<GerberParser>(file.toLocal8Bit().toStdString());`

**Comment by hsiang-lee** [comment]
> This error occurs when i compile with MSVC 2017 X64 on Visual studio.
> 
> `auto parser = std::make_unique<GerberParser>(file.toLocal8Bit().toStdString());`

Please copy the complete log here.

**Comment by tieutuanbao** [comment]
Sorry, my fail. Error occurs in run-time.

**Comment by hsiang-lee** [comment]
> Sorry, my fail. Error occurs in run-time.

Please upload the gerber file you use.

**Comment by hsiang-lee** [comment]
I guess you are compiling Debug version. But the dll file providered is release version. Linking release dll to debug exe on Windows will lead to runtime error. Recompile this project with release mode please. Thank you!
