### ISSUE TITLE
Threre is a bug in your program reading this gerver file(Gerver_TopLayer.GTL) 

### ISSUE THREAD

**Issue by Lafinger** [hsiang-lee/gerber-parser#8]
**Describe the bug**
threre is a bug in your program reading my gerver file

**Desktop (please complete the following information):**
 win10
 VS2019

**Additional context**
my gerver file:
G04 Layer: TopLayer*
G04 EasyEDA v6.5.9, 2022-08-17 17:40:46*
G04 9b6bc6ce99b44695a731befc9280ac48,93ff7820620a4e2d96899d85d3806809,10*  **!!!The program return when it reads this line.!!!**
G04 Gerber Generator version 0.2*
G04 Scale: 100 percent, Rotated: No, Reflected: No *
G04 Dimensions in millimeters *
G04 leading zeros omitted , absolute positions ,4 integer and 5 decimal *
%FSLAX45Y45*%
%MOMM*%
......

**Comment by Lafinger** [comment]
I try to submit my solution, but no tests

**Comment by hsiang-lee** [comment]
Indeed, there is a bug. Thank you very much!
